# Generated by Django 3.0.5 on 2020-07-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('id_str', models.CharField(max_length=21)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('retweet_count', models.IntegerField()),
                ('in_reply_to_user_id_str', models.CharField(max_length=50)),
                ('favorite_count', models.IntegerField()),
                ('is_retweet', models.BooleanField()),
            ],
        ),
    ]
